### ISSUE TITLE
Scroll bars disappearing when switching from different application

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-mac#476] opened 2019-09-17 18:46 UTC
When switching to xi from another application the scroll bars don't appear when scrolling:

![out](https://user-images.githubusercontent.com/1239705/65069931-8e4c2500-d940-11e9-95d7-5cb339dd6edf.gif)

Once the editor window is resized or some text is inserted the scroll bars will reappear when scrolling.

**Comment by nangtrongvuon** [comment] 2019-09-18 04:18
This is directly caused by a fix I merged a few weeks prior. Why this happens is the `ScrollView` looks for the `scroll` method to show the scroller. I have however overriden this `scroll` method to instead set the bounds origin directly. 

I'm not sure what triggers the appearance of the scrollers in `scroll`, but this bug would be fixed if I am able to replicate that.

**Comment by cmyr** [comment] 2019-09-22 15:28
@nangtrongvuon can you call `super` in your implementation of `scroll`? I'd check the docs and see what they say about this, but it could be the problem.

**Comment by nangtrongvuon** [comment] 2019-09-22 15:56
Actually, I’ve been doing that and the problem is a little bit trickier. Simply calling ‘super’ will make the scroll bar very jerky. There’s a hacky fix that I came up with (which is to call ‘setBoundsOrigin’ twice) but I suspect the real fix may be to get xi-mac to render continuously properly on scrolls, but I’m not quite sure how to do that yet.

Vào ngày 22 thg 9, 2019, lúc 22:28, Colin Rofls <notifications@github.com> đã viết:

﻿

@nangtrongvuon<https://github.com/nangtrongvuon> can you call super in your implementation of scroll? I'd check the docs and see what they say about this, but it could be the problem.

**Closed** 2019-09-25 02:55 UTC
