### ISSUE TITLE
Closing cmd-f bar is hiding first file line

### ISSUE THREAD

**Issue by MrSpock** [xi-editor/xi-mac#267] opened 2018-09-20 13:03 UTC
When you launch find bar (cmd-f) and then close it first line in a file is "hidden" below window bar.
You can't scroll to unhide it - you need to resize window to get access to fist line.
Steps in attached screenshots:
1. Open file (1 line in example)
2. Launch find bar (cmd-f)
3. Close bind bar clicking esc.

Line is hidden/not reachable.
![xi-issue](https://user-images.githubusercontent.com/681680/45820097-50dd9900-bce6-11e8-8478-dd6d08730812.png)

**Comment by cmyr** [comment] 2018-09-20 13:42
This is interesting, I can't reproduce.

Is this always the case for you, or only sometimes? What version of macOS are you running? Are you running the latest xi-mac build?

**Comment by MrSpock** [comment] 2018-09-20 15:19
I have such behaviour every time.
OS High Sierra 10.13.6

**Comment by MrSpock** [comment] 2018-09-20 15:36
To be honest I don't remember, a specially that today there was an upgrade to Xcode :)
I will download current master and rebuild it and see if that helps.

**Comment by cmyr** [comment] 2018-09-20 15:39
yea, I haven't tested the new version of Xcode so if you're running that it could be related?

**Comment by MrSpock** [comment] 2018-09-20 15:49
I've download repo 10 minutes ago, compiled with:
Xcode 10.0
Build version 10A255
Error still exists. In fact there are 2 lines missing. I think it depends on font size.
![xi-err](https://user-images.githubusercontent.com/681680/45830470-7924c200-bcfd-11e8-8ab6-1e93c442d8a8.png)

**Comment by cmyr** [comment] 2018-09-20 15:57
okay, this may be related to Xcode 10.

**Comment by jansol** [comment] 2018-09-21 04:11
Can't repro with Xcode 10

macOS 10.13.6
Font is Fira Mono 11pt

**Comment by cmyr** [comment] 2018-09-21 15:14
@MrSpock what is in your config?

**Comment by jansol** [comment] 2018-10-12 04:00
Nope, can't reproduce with default config either. @MrSpock can you try again?

What I did notice is that the find bar has lost its color in Mojave's dark mode (again) but I expect the Mojave PR to deal with that.

**Comment by jansol** [comment] 2019-01-12 06:10
Closing this as nobody has reported being able to reproduce this and there has been a good bit of work on the find bar since. Please reopen if the bug resurfaces.

**Closed by jansol** 2019-01-12 06:10 UTC
Labels: bug, needs reproduction
